// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDU2Yd76WlfPRCN_QdiTuS0WENqFcUFoIo',
    appId: '1:939647790783:web:e17059d50563b46c96a00a',
    messagingSenderId: '939647790783',
    projectId: 'sovietunion-8362f',
    authDomain: 'sovietunion-8362f.firebaseapp.com',
    storageBucket: 'sovietunion-8362f.firebasestorage.app',
    measurementId: 'G-W37D8NGMMQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAk9gP0M4IAfS00ZlBt8y-VloBKJXTQc_I',
    appId: '1:939647790783:android:9607fbe762fd861a96a00a',
    messagingSenderId: '939647790783',
    projectId: 'sovietunion-8362f',
    storageBucket: 'sovietunion-8362f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBae4zIbcBndtR3Uxk9y2GEywuH5kz6TLs',
    appId: '1:939647790783:ios:12aa38c69354807496a00a',
    messagingSenderId: '939647790783',
    projectId: 'sovietunion-8362f',
    storageBucket: 'sovietunion-8362f.firebasestorage.app',
    iosBundleId: 'com.example.sovietunion',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBae4zIbcBndtR3Uxk9y2GEywuH5kz6TLs',
    appId: '1:939647790783:ios:12aa38c69354807496a00a',
    messagingSenderId: '939647790783',
    projectId: 'sovietunion-8362f',
    storageBucket: 'sovietunion-8362f.firebasestorage.app',
    iosBundleId: 'com.example.sovietunion',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDU2Yd76WlfPRCN_QdiTuS0WENqFcUFoIo',
    appId: '1:939647790783:web:43ce877377a18c9b96a00a',
    messagingSenderId: '939647790783',
    projectId: 'sovietunion-8362f',
    authDomain: 'sovietunion-8362f.firebaseapp.com',
    storageBucket: 'sovietunion-8362f.firebasestorage.app',
    measurementId: 'G-HW1NX4W5JS',
  );
}
