// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBPM3vXgTkEnBsNgiJZxpt8GeDhgp06J20',
    appId: '1:3382186843:web:3fe5435a1a0b7d2681c07e',
    messagingSenderId: '3382186843',
    projectId: 'sovietunion-87718',
    authDomain: 'sovietunion-87718.firebaseapp.com',
    storageBucket: 'sovietunion-87718.firebasestorage.app',
    measurementId: 'G-EWY1KZWJMM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBF2oHrKrWCtHeWjtyixN5LUtAs7syff6Y',
    appId: '1:3382186843:android:553a8b3f6caa917681c07e',
    messagingSenderId: '3382186843',
    projectId: 'sovietunion-87718',
    storageBucket: 'sovietunion-87718.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBc2PVQ8rf1ZWiKLKkkvqQPMqc72F6Lz5c',
    appId: '1:3382186843:ios:5a73dcca63eb9de981c07e',
    messagingSenderId: '3382186843',
    projectId: 'sovietunion-87718',
    storageBucket: 'sovietunion-87718.firebasestorage.app',
    iosBundleId: 'com.example.sovietunion',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBc2PVQ8rf1ZWiKLKkkvqQPMqc72F6Lz5c',
    appId: '1:3382186843:ios:5a73dcca63eb9de981c07e',
    messagingSenderId: '3382186843',
    projectId: 'sovietunion-87718',
    storageBucket: 'sovietunion-87718.firebasestorage.app',
    iosBundleId: 'com.example.sovietunion',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBPM3vXgTkEnBsNgiJZxpt8GeDhgp06J20',
    appId: '1:3382186843:web:e14ed99ef4e18f6c81c07e',
    messagingSenderId: '3382186843',
    projectId: 'sovietunion-87718',
    authDomain: 'sovietunion-87718.firebaseapp.com',
    storageBucket: 'sovietunion-87718.firebasestorage.app',
    measurementId: 'G-2M8D76RW8Q',
  );
}
